export const seoKeywords = [
  "Abdullah Ayoola",
  "Web Developer",
  "Web Designer",
  "Portfolio",
  "reactmode",
  "UI designer",
  "Frontend developer",
  "Backend developer",
  "Fullstack developer",
  "React developer",
  "Next.js developer",
  "Node.js developer",
  "Express.js developer",
  "MongoDB developer",
  "MERN stack developer",
  "Software developer",
  "Software engineer",
  "Web developer in Nigeria",
  "Web developer in Lagos",
];
